# Generated by Django 5.2.5 on 2025-08-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_aboutus_client_contact_contenthistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='media',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='thumbnail_large',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/large/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='media',
            name='thumbnail_medium',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/medium/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='media',
            name='thumbnail_small',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/small/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio')], max_length=50, null=True),
        ),
    ]
